swagger: '2.0'
info:
  version: v1
  title: 用户中心v1接口
  description: 用户中心v1接口
  termsOfService: http://dealmoon.com
basePath: /v1
schemes:
  - http
  - https
consumes:
  - multipart/form-data
produces:
  - application/json
security:
  - dm_token: []
  - dm_udid: []
  - dm_type: []
  - dm_ip: []
securityDefinitions:
  dm_token:
    type: apiKey
    in: query
    name: dm_token
  dm_udid:
    type: apiKey
    in: query
    name: dm_udid
  dm_type:
    type: apiKey
    in: query
    name: dm_type
  dm_ip:
    type: apiKey
    in: query
    name: dm_ip
paths:
  /user/info:
    post:
      parameters:
      - name: token
        in: formData
        description: 用户登录token
        required: true
        type: string
      description: 通过token获取用户信息
      responses:
        default:
          description: successful operation
          schema:
            $ref: '#/definitions/userInfo'
  /user/login:
    post:
      parameters:
      - name: email
        in: formData
        description: 用户email
        required: true
        type: string
      - name: password
        in: formData
        description: 用户密码
        required: true
        type: string
      - name: bindUser
        in: formData
        description: 是否绑定用户
        type: string
        enum:
          - 0
          - 1
      - name: bindInfo[openId]
        in: formData
        description: 第三方绑定id
        required: true
        type: string
      description: 通过token获取用户信息
      responses:
        default:
          description: successful operation
          schema:
            $ref: '#/definitions/userInfo'      
definitions:
  ERROR:
    type: object
    required:
      - code
    properties:
      code:
        type: integer
      message:
        type: string
  ACCOUNT:
    type: object
    required:
      - openId
    properties:
      openId:
        type: string
      type:
        type: string
        enum:
          - sina
          - qq
          - renren
          - douban
          - facebook
          - twitter
          - wechat
      unionid:
        type: string
        description: 微信使用的unionid
      nickname:
        type: string

  USER:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      isAdmin:
        type: boolean
      name:
        type: string
      email:
        type: string
      status:
        type: string
        description: 用户激活状态
        enum:
         - active
         - N-active
      createTime:
        type: integer
      isDefaultAvatar:
        type: boolean
      avatar:
        type: string
      sex:
        type: string
        enum:
          - men
          - women
          - secret
      birthday:
        type: string
      language:
        type: string
        enum:
          - cn
          - en
      mobile:
        type: string
      introduce:
        type: string
      isSubscribingNewsletter:
        type: integer
        enum:
          - 0
          - 1
      location:
        type: string
      thirdPartyAccounts:
        type: array
        items:
          $ref: '#/definitions/ACCOUNT'
        
  
  
  userInfo :
    type: object
    required : 
      - result
    properties:
     result:
       $ref: '#/definitions/ERROR'
     userInfo:
       $ref: '#/definitions/USER'
  result :
    type: object
    required : 
      - result
    properties:
     result:
       $ref: '#/definitions/ERROR'
  